pull request first time
shrikanttechincal/firstProject pull request #2
Opened 2020-09-25 12:59 UTC by shrikanttechincal

pulling request

2020-09-25 14:15 UTC, akhil7000 requested changes

2020-09-25 14:15 UTC, akhil7000 commented on FlipkartSelenide.ipr
>      <option name="TEST_RUNNER" value="UI" />
Add this file to gitIgnore - not to be committed and pushed.
All the intellij files, target and other user generated files has to be added to gitIgnore

2020-09-25 14:15 UTC, akhil7000 commented on FlipkartSelenide.iws
>  <?xml version="1.0" encoding="UTF-8"?>
Add this file to gitIgnore - not to be committed and pushed

2020-09-25 14:15 UTC, akhil7000 commented on src/main/java/com/test/Action.java
>      //Constructor
remove this comment

2020-09-25 14:15 UTC, akhil7000 commented on src/main/java/com/test/Action.java
> +public String pName1() {
use proper indentation and meaningful names for all the functions

2020-09-25 14:15 UTC, akhil7000 commented on src/main/java/com/test/Action.java
> +    public WebElement addTocart2() {
Why we have two functions for addToCart?

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/ExcelFile.java
> +    ///hello
remove this comment

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
> +        Assert.assertTrue(b);
Instead of use two lines, merge into a single line :
Assert.assertTrue(getDetails2);

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
>  import org.testng.Assert;
Use proper identation for the whole class

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
> +            Thread.sleep(5000);
why don't you use the delay function here?

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
> +//        Assert.assertTrue(a1.equals(a2));
remove commented lines

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
> +        try {
use delay function here

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
> +            Thread.sleep(3000);
use delay function

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
> +        System.out.println("x3    "+          x3 );
why so much white spacing?

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
> +        String x3=x1+x2;
Use some meaningful names instead of x1,x2,x3

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
>          Action a = new Action(driver);
Use a meaningful name for both the class and object like - FlipkartPage or something

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
> +            String p1= it3.next();
Please use a meaningful names for all strings

2020-09-25 14:15 UTC, akhil7000 commented on src/test/java/com/test/Flipkart1.java
>      public Boolean getDetails() {
remove this unused function

2020-09-26 05:35 UTC, shrikanttechincal commented on src/main/java/com/test/Action.java
> +    public WebElement addTocart2() {
because i have selcected 2 products so adding  those productss in cart

2020-09-26 09:26 UTC, merged